import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.0.0',
  date: '2025-11-23T15:49:07.766Z',
};
export default meta;
